services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: dineflow-api:prod
    container_name: dineflow-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:${BACKEND_PORT:-8500}:8080"
    environment:
      PORT: "8080"
      APP_ENV: "production"
      MONGODB_URI: ${MONGODB_URI:-mongodb://dineflow-mongo:27017/dineflow}
      MONGODB_DATABASE: ${MONGODB_DATABASE:-dineflow}
      REDIS_URL: ${REDIS_URL:-redis://dineflow-redis:6379}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-dineflow_jwt_access_secret_key_prod_64char_minimum_padding_string}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dineflow_jwt_refresh_secret_key_prod_64char_minimum_padding_string}
      JWT_ACCESS_TTL_MINUTES: ${JWT_ACCESS_TTL_MINUTES:-15}
      JWT_REFRESH_TTL_DAYS: ${JWT_REFRESH_TTL_DAYS:-7}
      SUPER_ADMIN_SECRET: ${SUPER_ADMIN_SECRET:-dineflow_super_admin_secret_key_prod}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-https://dine.rovixatech.com,http://127.0.0.1:3000}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@dine.rovixatech.com}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-DineFlow}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      FRONTEND_URL: ${FRONTEND_URL:-http://dineflow-web:3000}
    depends_on:
      - mongo
      - redis

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://dine.rovixatech.com/api/v1}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-wss://dine.rovixatech.com}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-https://dine.rovixatech.com}
        NEXT_PUBLIC_ORDERING_URL: ${NEXT_PUBLIC_ORDERING_URL:-https://dine.rovixatech.com/order}
        NEXT_PUBLIC_APP_NAME: "DineFlow"
    image: dineflow-web:prod
    container_name: dineflow-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3500}:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "production"
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://dine.rovixatech.com/api/v1}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-wss://dine.rovixatech.com}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-https://dine.rovixatech.com}
      NEXT_PUBLIC_ORDERING_URL: ${NEXT_PUBLIC_ORDERING_URL:-https://dine.rovixatech.com/order}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    depends_on:
      - api

  mongo:
    image: mongo:7.0
    container_name: dineflow-mongo
    restart: unless-stopped
    volumes:
      - dineflow_mongodata:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: dineflow-redis
    restart: unless-stopped
    volumes:
      - dineflow_redisdata:/data

volumes:
  dineflow_mongodata:
  dineflow_redisdata:
